on:
  push:
    branches:
      - main
    paths-ignore:
      - 'kubernetes/**'
      - '.github/**'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/ndi-do/2024-bergerie-api:latest
          provenance: false

    

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: dist/*
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     tag: ${{ github.sha }}
      #     release_name: ${{ github.sha }}
      #     body: ${{ github.sha }}